### ISSUE TITLE
Should all datasets be of limited size so that the package immediately loads in, or should I incorporate datasets with several million observations, although then initial package loading in RStudio might take more than several seconds?

### ISSUE THREAD

**Issue by fuchsfranklin** [datatrail-jhu/BaltimoreTrails#8]
- An alternative to this would be to take a random subset of the larger datasets where possible.

**Comment by cansavvy** [comment]
Yes, we need to consider this somewhat. On one hand the students will be using chromebooks, but they will be accessing the cloud. 

Looks like OpenBaltimore has an API: https://data.baltimorecity.gov/datasets/baltimore::baltimore-city-employee-salaries-2/api 

So we can have it so the bigger datasets are not downloaded unless they are being used. 

We might want to include a warning when any large datasets are downloaded so people are aware that they have downloaded a large file. We should also tell them where the file has been stored so if they want to delete it they can.

**Comment by cansavvy** [comment]
How big are the datasets that are bigger? Just so we have an idea?

**Comment by fuchsfranklin** [comment]
I will test the jsonlite solution of directly loading the data into the R session we discussed as a first step.
